routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// Admin routes
Route::prefix('admin')->group(function () {

    // Ajax routes
    Route::post('/cityOfCountry', 'Backend\AjaxController@getCityOfCountry');
    Route::post('/hotelOfCountry', 'Backend\AjaxController@gethotelOfCountry');
    Route::post('/inclusions', 'Backend\AjaxController@addinclusion');
    Route::post('/exclusions', 'Backend\AjaxController@addexclusion');
    Route::post('/labels', 'Backend\AjaxController@addlabel');
    Route::post('/days', 'Backend\AjaxController@addday');
    Route::post('/transfers', 'Backend\AjaxController@addtransfer');
    Route::post('/tours-of-package', 'Backend\AjaxController@addtourtoday');
    Route::post('/admin-hotels', 'Backend\AjaxController@addhotel');
    Route::post('/tourofcity', 'Backend\AjaxController@gettourofcity');
    Route::post('/flights', 'Backend\AjaxController@addflight');
    Route::post('/segment', 'Backend\AjaxController@addsegmenttoflight');
    Route::post('/hotelsegments', 'Backend\AjaxController@addsegmenttofhotel');
    Route::post('/hotelpricing', 'Backend\AjaxController@addpricingofhotel');

    Route::post('/type-to-home', 'Backend\AjaxController@addtypetohome');
    Route::post('/activity-tour-to-home', 'Backend\AjaxController@addActivityTourToHome');
    Route::post('/country-to-home', 'Backend\AjaxController@addcountrytohome');
    Route::post('/main-country-to-home', 'Backend\AjaxController@addMainCountryToHome');
    Route::post('/nationalitiesOfCountry', 'Backend\AjaxController@getNationalitiesOfCountry');
    Route::post('/activitycityOfCountry', 'Backend\AjaxController@getActivityCityOfCountry');
    Route::post('/activitycategory', 'Backend\AjaxController@addTourCategory');
    Route::post('/activitystatus', 'Backend\AjaxController@updateGlobalStatus');
    Route::post('/activePackage', 'Backend\AjaxController@updatePackageStatus');
    Route::post('/outbound-visa-status', 'Backend\AjaxController@updateGlobalStatus');
    Route::post('/uae-visa-status', 'Backend\AjaxController@updateGlobalStatus');
    Route::post('/accepted-enquiry', 'Backend\AjaxController@acceptedEnquiry');

    Route::post('/visa-type-to-home', 'Backend\AjaxController@addVisaTypeToHome');
    Route::post('/visa-nationality-to-home', 'Backend\AjaxController@addVisaNationalityToHome');

    Route::post('/nationality-type', 'Backend\AjaxController@nationalityType');

    Route::post('/enquiries/accepted-enquiry', 'Backend\AjaxController@acceptedEnquiry');


    Route::get('/', 'Users\Admin\AdminController@index')->name('admin.dashboard');

    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');

    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/register', 'Auth\AdminRegisterController@showRegisterForm')->name('admin.register');
    Route::post('/register', 'Auth\AdminRegisterController@register')->name('admin.register.submit');
    Route::name('admin.')->group(function () {
        Route::group(['middleware' => 'auth:admin'], function () {
            Route::get('blogs/information', 'Backend\BlogController@showInfoForm')->name('blogs.info')->middleware(["permission:blogs.info"]);
            Route::patch('blogs/information', 'Backend\BlogController@saveInfo')->name('blogs.info.save')->middleware(["permission:blogs.info"]);

            Route::get('/order', 'Backend\CountryController@showOrderForm')->name('countries.order')->middleware(["permission:countries.order"]);
            Route::patch('/order', 'Backend\CountryController@saveOrder')->name('countries.order.save')->middleware(["permission:countries.order"]);

            Route::get('/services/order', 'Backend\ServiceController@showOrderForm')->name('services.order');
            Route::patch('/services/order', 'Backend\ServiceController@saveOrder')->name('services.order.save');

            Route::get('packages/information', 'Backend\GeneralInformationController@showPackagesInfoForm')->name('packages.info');
            Route::patch('packages/information', 'Backend\GeneralInformationController@savePackagesInfo')->name('packages.info.save');

            Route::resource('countries', Backend\CountryController::class)->middleware(["check_country_permission"]);

            Route::resource('cities', Backend\CityController::class)->middleware(["check_normal_permission:cities"]);
            Route::resource('users', Backend\AdminController::class)->middleware(['check_user_permission:admins']);
            Route::resource('pages', Backend\PageController::class)->only(['edit', 'update'])->middleware(['check_edit_permission:pages']);
            Route::resource('tours', Backend\TourController::class)->middleware(["check_normal_permission:tours"]);
            Route::resource('blogs', Backend\BlogController::class)->middleware(["check_blog_permission"]);;
            Route::resource('roles', Backend\RoleController::class)->middleware(['check_user_permission:roles']);
            Route::resource('blogs.sliders', Backend\BlogSliderController::class)->middleware(["permission:blogs.slider"]);
            Route::resource('blogs.comments', Backend\CommentController::class)->middleware(["permission:blogs.comment"]);
            Route::resource('hotels', Backend\HotelController::class)->middleware(["check_normal_permission:hotels"]);
            Route::get('packages/order/{country}', 'Backend\PackageController@showOrderForm')->name('packages.order')->middleware(['permission:packages.order']);
            Route::patch('packages/order', 'Backend\PackageController@saveOrder')->name('packages.order.save')->middleware(['permission:packages.order']);
            Route::resource('packages', Backend\PackageController::class)->middleware(['check_package_permission']);
            Route::resource('packages.sliders', Backend\PackageSliderController::class)->middleware(['permission:packages.slider']);
            Route::resource('sliders', Backend\SliderController::class)->middleware(["check_normal_permission:sliders"]);;
            Route::resource('settings', Backend\SiteSettingController::class)->only(['index', 'edit', 'update'])->middleware(['check_edit_permission:setting']);
            Route::resource('models', Backend\GlobalModelController::class)->only(['update'])->middleware(['role:super-admin']);
            Route::resource('enquiries', Backend\EnquiryController::class)->except('create', 'store', 'edit', 'update');
            Route::resource('partners', Backend\PartnerController::class)->middleware(["check_normal_permission:partners"]);
            Route::resource('services', Backend\ServiceController::class)->middleware(["check_normal_permission:services"]);
            Route::resource('newsletter', Backend\NewsletterController::class)->only(['index']);

            Route::get('home-images', 'Backend\GeneralInformationController@showInfoForm')->name('home.info');
            Route::patch('home-images', 'Backend\GeneralInformationController@saveInfo')->name('home.info.save');

            Route::get('orders', 'Backend\EnquiryController@index_order')->name('orders.index');
            Route::get('orders/{id}', 'Backend\EnquiryController@show')->name('orders.show');

            Route::prefix('visa')->group(function () {
                Route::get('information', 'Backend\VisaOutboundController@showInfoForm')->name('visa.info')->middleware(["permission:visa.info"]);
                Route::patch('information', 'Backend\VisaOutboundController@saveInfo')->name('visa.info.save')->middleware(["permission:visa.info"]);
                Route::get('uae/information', 'Backend\VisaUaeController@showInfoForm')->name('visa.uae.info')->middleware(["permission:visa.info"]);
                Route::patch('uae/information', 'Backend\VisaUaeController@saveInfo')->name('visa.uae.info.save')->middleware(["permission:visa.info"]);

                Route::get('uaes/application', 'Backend\VisaUaeApplicationController@index')->name('visa.uae.application.index');
                Route::get('uaes/application/{id}', 'Backend\VisaUaeApplicationController@view')->name('visa.uae.application.view');

                Route::get('outbounds/application', 'Backend\VisaOutboundApplicationController@index')->name('visa.outbound.application.index');
                Route::get('outbounds/application/{id}', 'Backend\VisaOutboundApplicationController@view')->name('visa.outbound.application.view');


                Route::resource('visacountries', Backend\VisaCountryController::class)->middleware(["check_normal_permission:visa.countries"]);
                Route::resource('nationalities', Backend\VisaNationalityController::class)->middleware(["check_normal_permission:visa.nationalities"]);
                Route::resource('uaeNationalities', Backend\VisaUaeNationalityController::class)->middleware(["check_normal_permission:visa.uae.nationalities"]);
                Route::resource('types', Backend\VisaTypeController::class)->middleware(["check_normal_permission:visa.types"]);
                Route::resource('uaeTypes', Backend\VisaUaeTypeController::class)->middleware(["check_normal_permission:visa.uaeTypes"]);
                Route::resource('uaeRequirements', Backend\VisaUaeRequirementController::class)->middleware(["check_normal_permission:visa.uaeRequirements"]);
                Route::resource('outbounds', Backend\VisaOutboundController::class)->middleware(["check_normal_permission:visa.outbounds"]);

                Route::get('uaes/configuration', 'Backend\VisaUaeController@showConfigForm')->name('uaes.config');

app/Http/Controllers/Backend/ActivityCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\ActivityCategory;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ActivityCategoryController extends Controller
{
    public function __construct()
    {

            $this->middleware('auth:admin');
            $this->middleware('permission:activities.categories.create.en|activities.categories.create.ar')->only(['create', 'store']);
            $this->middleware('permission:activities.categories.edit.en|activities.categories.edit.ar')->only(['edit', 'update']);
            $this->middleware('permission:activities.categories.delete')->only('destroy');

    }

    public function index()
    {
        $categories = ActivityCategory::orderBy('id', 'DESC')->paginate(20);
        return view('backend.activity.category.index')->with(['categories' => $categories]);
    }

    public function create()
    {
        return view('backend.activity.category.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name_ar' => 'required',
            'name_en' => 'required'
        ]);
        $dataIn = $request->all();
        $dataIn['created_by'] = Auth::guard('admin')->user()->getAuthIdentifier();
        $dataIn['updated_by'] = Auth::guard('admin')->user()->getAuthIdentifier();

        $category = ActivityCategory::create($dataIn);
        return redirect()->route('admin.activitycategories.index');
    }

    public function edit($id)
    {
        $category = ActivityCategory::findOrFail($id);
        return view('backend.activity.category.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name_ar' => 'required',
            'name_en' => 'required'
        ]);
        $dataIn = $request->all();
        $dataIn['updated_by'] = Auth::guard('admin')->user()->getAuthIdentifier();

        $category = ActivityCategory::findOrFail($id);
        $category->update($dataIn);
        return redirect()->route('admin.activitycategories.index');
    }

    public function destroy($id)
    {
        $category = ActivityCategory::findOrFail($id);
        $category->delete();
        return redirect()->route('admin.activitycategories.index');
    }

    public function restorecategory($id)
    {
        $category = ActivityCategory::findOrFail($id);
        $category->restore();
        return redirect()->route('admin.activitycategories.index');
    }
}

app/Http/Controllers/Backend/ActivityCityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\ActivityCity;
use App\ActivityCountry;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ActivityCityController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('permission:activities.cities.create.en|activities.cities.create.ar')->only(['create','store']);
        $this->middleware('permission:activities.cities.edit.en|activities.cities.edit.ar')->only(['edit','update']);
        $this->middleware('permission:activities.cities.delete')->only('destroy');
    }
    public function index()
    {
        if (request()->country) {
//            if admin
//            $cities = ActivityCity::where('activity_country_id', \request()->country)->withTrashed()->get();
            $cities = ActivityCity::where('activity_country_id', \request()->country)->orderBy('id', 'DESC')->get();
            $country = ActivityCountry::findOrFail(\request()->country);
        } else {
            $cities = ActivityCity::orderBy('id', 'DESC')->get();
            $country = null;
        }
        return view('backend.activity.city.index')->with(['cities' => $cities, 'country' => $country]);
    }

    public function create()
    {
        if (request()->country) {
            $country = ActivityCountry::findOrFail(request()->country);
            return view('backend.activity.city.create', compact('country'));
        } else {
            return redirect()->route('admin.activitycountries.index');
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'activity_country_id' => 'required'
        ]);

        $city = ActivityCity::create($request->all());
        return redirect()->route('admin.activitycities.index', ['country' => $request->activity_country_id]);
    }

    public function edit($id)
    {
        $city = ActivityCity::findOrFail($id);
        return view('backend.activity.city.edit', compact('city'));
    }

    public function update(Request $request, $id)
    {
        $city = ActivityCity::findOrFail($id);
        $city->update($request->all());
        return redirect()->route('admin.activitycities.index',['country' => $city->activity_country_id]);
    }

    public function destroy($id)
    {
        $city = ActivityCity::findOrFail($id);
        $city->delete();
        return redirect()->route('admin.activitycities.index', ['country' => $city->activity_country_id]);
    }
    public function restorecity($id){
        $city = ActivityCity::findOrFail($id);
        $city->restore();
        return redirect()->route('admin.activitycities.index',['country' => $city->activity_country_id]);
    }
}

app/Http/Controllers/Backend/ActivityCountryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\ActivityCountry;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ActivityCountryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('permission:activities.countries.create.en|activities.countries.create.ar')->only(['create','store']);
        $this->middleware('permission:activities.countries.edit.en|activities.countries.edit.ar')->only(['edit','update']);
        $this->middleware('permission:activities.countries.delete')->only('destroy');
    }

    public function index()
    {
        $countries = ActivityCountry::orderBy('id', 'DESC')->paginate(20);
        return view('backend.activity.country.index')->with(['countries' => $countries]);
    }

    public function create()
    {
        return view('backend.activity.country.create');
    }

    public function store(Request $request)
    {
        $dataIn = $request->all();
        $dataIn['created_by'] = Auth::guard('admin')->user()->getAuthIdentifier();
        $dataIn['updated_by'] = Auth::guard('admin')->user()->getAuthIdentifier();

        $country = ActivityCountry::create($dataIn);
        return redirect()->route('admin.activitycountries.index');
    }

    public function edit($id)
    {
        $country = ActivityCountry::findOrFail($id);
        return view('backend.activity.country.edit', compact('country'));
    }

    public function update(Request $request, $id)
    {
        $dataIn = $request->all();
        $dataIn['updated_by'] = Auth::guard('admin')->user()->getAuthIdentifier();

        $country = ActivityCountry::findOrFail($id);
        $country->update($dataIn);
        return redirect()->route('admin.activitycountries.index');
    }

    public function destroy($id)
    {
        $country = ActivityCountry::findOrFail($id);
        $country->delete();
        return redirect()->route('admin.activitycountries.index');
    }

    public function restorecountry($id)
    {
        $country = ActivityCountry::findOrFail($id);
        $country->restore();
        return redirect()->route('admin.activitycountries.index');
    }
}

app/Http/Controllers/Backend/LabelController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class LabelController extends Controller
{
    //
}

resources/views/backend/enquiry/index.blade.php
@extends('backend.layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Enquiries</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{url('/admin')}}">Home</a></li>
                        <li class="breadcrumb-item active">Enquiries</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>Full name</th>
                                    <th>Email</th>
                                    <th>Package</th>
                                    <th>Date</th>
                                    <th>Manage</th>
                                    <th>Status</th>
                                    <th>Accepted</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($enquiries)
                                    @foreach($enquiries as $enquiry)
                                        <tr>
                                            <td>{{$enquiry->enquiry_name()}}</td>
                                            <td>{{$enquiry->enquiry_email()}}</td>
                                            @if($enquiry->custom == '0')
                                                <a href="{{route('details',['symbol' => $enquiry->package->symbol,'hotel' => $enquiry->hotel->symbol])}}">
                                                    <td>{{$enquiry->package->name_en}}</td>
                                                </a>
                                            @else
                                                <td><span style="color: #ff5400">Custom</span></td>
                                            @endif
                                            <td>{{$enquiry->created_at}}</td>
                                            <td>
                                                <a href="{{route('admin.enquiries.show', $enquiry->id)}}"
                                                   class="btn btn-warning">View</a>
                                                <form action="{{route('admin.enquiries.destroy', $enquiry->id)}}"
                                                      method="post" style="width: 50%;display: inline-block;">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger">Delete</button>
                                                </form>
                                            </td>
                                            <td>
                                                @if($enquiry->view == '1')
                                                    <span style="color: #04911a">Viewed</span>
                                                @else
                                                    <span style="color: #911e04">Not Viewed</span>
                                                @endif
                                            </td>
                                            <td>
                                                @if($enquiry->accepted == '1')
                                                    <input id="enquiry-switch" class="enquiry-switch" type="checkbox"
                                                           name="my-checkbox" checked
                                                           data-bootstrap-switch data-off-color="danger"
                                                           data-on-color="success" data-id="{{$enquiry->id}}"
                                                           data-on-value="1" data-off-value="0">
                                                @else
                                                    <input id="enquiry-switch" class="enquiry-switch" type="checkbox"
                                                           name="my-checkbox" data-bootstrap-switch
                                                           data-off-color="danger" data-on-color="success"
                                                           data-id="{{$enquiry->id}}"
                                                           data-on-value="1" data-off-value="0">
                                                @endif
                                            </td>

                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>

                            </table>
                            <div class="mt-4"></div>
                            {!! $enquiries->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection